### ISSUE TITLE
Suggestion: better error case

### ISSUE THREAD

**Issue by wavebeem** [minamorl/trishula#10]
I think it would make more sense to use two separate classes for parser results. It doesn't make sense to have a `value` property when the parse fails, and you could use `if isinstance(result, T.Fail)` instead of `if result.status is T.Status.FAILURE`

```py
class Success:
  value
  index

class Failure:
  message
  index
```

**Comment by wavebeem** [comment]
This way it would be an error to access `someResult.value` if it is an error. I think this would help people use Trishula correctly.

**Comment by minamorl** [comment]
Should I implement this as an exception?

**Comment by wavebeem** [comment]
I think it would be easier to not use exceptions 😄
