### ISSUE TITLE
How to use recursion?

### ISSUE THREAD

**Issue by wavebeem** [minamorl/trishula#3]
There needs to be some way to choose what parser to use next, like Parsimmon's `.chain`. I'm trying to implement a list parser and I'm stuck on nesting the arrays:

```
UnboundLocalError: local variable 'p_list' referenced before assignment
```

In Parsimmon you need `.lazy` for recursion and `.chain` is like an `if` statement, so I think Trishula will need something like each of them

```py
import trishula as T


def grammar():
    p_list = (
        ((
            T.Value("[") >>
            p_list >>
            T.Value("]")
        ) @ m(lambda x: [x[0][1]])) |
        (T.Value("[]") @ m(lambda: []))
    )
    return p_list


def main():
    print(dir(T))
    print()
    result = T.Parser().parse(grammar(), "[[[]]]")
    print(vars(result))


def m(f):
    return lambda x: T.Node(x.status, x.index, f(x.value))


main()
```

**Comment by minamorl** [comment]
How do you think this solution? I made a class "Ref" for lazy evaluation.
https://github.com/minamorl/trishula/blob/6077f1c291d396651acd687a009c4213aa1fbe89/trishula/grammar.py#L37-L42
```python
def grammar():
   return (
        (T.Value("[]") @ m(lambda x: [])) |
        ((
            T.Value("[") >>
            T.Ref(grammar) >>
            T.Value("]")
        ) @ m(lambda x: [x[0][1]]))
    )
```
(T.Ref is included in version 0.0.2)

**Comment by wavebeem** [comment]
That makes sense! Thanks

**Comment by wavebeem** [comment]
Oh actually I just thought, you might want to memoize the Ref class to store the value so it doesn't call self.ref() every time you parse
